apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: gitlab-runner-amd64
spec:
  forProvider:
    chart:
      name: gitlab-runner
      repository: https://charts.gitlab.io/
      version: "0.81.0"
    skipCreateNamespace: false
    namespace: gitlab-runner
    wait: true
    waitTimeout: "5m0s"
    valuesFrom:
    - secretKeyRef:
        key: svalues.yaml
        name: gitlab-runner-amd64-values
        namespace: crossplane-system
        optional: false
    values:
      # RBAC configuration for the top-level SA
      rbac:
        create: true
      # This is the GitLab Runners pod SA - use the default one (this will create the job pods)
      serviceAccount:
        create: true

      # set environment variables
      extraEnv:
        # https://docs.gitlab.com/runner/executors/kubernetes/#configure-the-executor-service-account
        KUBERNETES_SERVICE_ACCOUNT: redacted-gitlab-runner-sa # use the IamSa we created via Crossplane

      # GitLab instance configuration
      gitlabUrl: https://git.redacted.example.com/

      # AMD64-specific node selector for runner pod
      nodeSelector:
        lifecycle: OnDemand
        karpenter.sh/nodepool: system-pool
        # kubernetes.io/arch: amd64

      # Pod annotations for EKS
      podAnnotations:
        eks.amazonaws.com/compute-type: ec2
        eks.amazonaws.com/nodegroup: default
        karpenter.sh/do-not-evict: "true"

      # Deployment configuration
      replicas: 1

      # Resource limits
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi

      # Runner configuration with AMD64-specific tag
      runners:
        tags: "redacted-sandbox-amd64"
        config: |
          [[runners]]
            [runners.kubernetes]
              namespace = "{{.Release.Namespace}}"
              image = "ubuntu:22.04"
              privileged = false
              [runners.kubernetes.pod_annotations]
                "karpenter.sh/do-not-evict" = "true"
                "eks.amazonaws.com/compute-type" = "ec2"
              [runners.kubernetes.node_selector]
                "karpenter.sh/nodepool" = "multiarch-spot"
                "lifecycle" = "Ec2Spot"
                "kubernetes.io/arch" = "amd64"
              [runners.kubernetes.node_tolerations]
                "cicd-builds=true" = "NoSchedule"

      # Security context
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        runAsNonRoot: true

  managementPolicies:
  - '*'
  providerConfigRef:
    name: redacted-aws-admin
  rollbackLimit: 3
